### ISSUE TITLE
Share icon missing on ps4 button prompts

### ISSUE THREAD

**Issue by Vwert** [losh11/EldenRingGamepadUI#3]
![start_protected_game exe Screenshot 2022 03 15 - 11 30 54 74 (2)](https://user-images.githubusercontent.com/43323401/158372827-d282d7ed-865d-4506-8503-232636dcd555.png)

**Comment by SiliconExarch** [comment]
> ![start_protected_game exe Screenshot 2022 03 15 - 11 30 54 74 (2)](https://user-images.githubusercontent.com/43323401/158372827-d282d7ed-865d-4506-8503-232636dcd555.png)

That's because the map's not bound to the share button on PS4/5 but the touchpad. If you're running the game on Steam with the official Input profile then it should be the same.
