### ISSUE TITLE
Needs to be updated to new patch, Graphical inconsistencies.

### ISSUE THREAD

**Issue by coolbond1** [losh11/EldenRingGamepadUI#4]
for example the Starlight Shard looks like a meat pile and armor pieces have the wrong graphics, im guessing IDs got shifted around in the patch.

**Comment by losh11** [comment]
I’ll take a look today.

**Comment by coolbond1** [comment]
sorry to bother you with this again but i was wondering if you had an ETA on when this gets fixed? sure its nothing major but its hard to find things when the images are not what they are supposed to be.

**Comment by smallerYeet** [comment]
I have the same problem and there are major issues. Mostly textures that are swaped and the Compass is slighty more down

**Comment by losh11** [comment]
This isn’t a issue with the mod. What seem to have happened is that you
have extracted the Elden Ring data archive, and then manually replaced the
texture mapping files with the ones I’ve provided. However the data in the
archive has changed since the update.

You must delete the unpacked data folders and patch again with this mod,
every time Elden Ring updates, otherwise you will see visual errors.

Sadly this is the issue when there is not option for a Elden Ring mod
engine.

**Comment by Shini1313** [comment]
I have just now installed the mod into a freshly unpacked version of the game. Followed the tutorial, unpack with Yabber, add .dcx and compression as SekiroKRAK. After patching with UXM this resulted in weird graphical errors, e.g. the symbols for sites of grace on the map were replaced with the symbol of the Haligtree, Runes lost after death were marked with the NPC Icon on the map and compass and more. So this does appear to be a Problem with the mod.

**Comment by Shini1313** [comment]
Also just tested a different mod that uses UXM and then replaces files, that one worked perfectly fine

**Comment by Shini1313** [comment]
Okay, so after some testing, I have identified the problem. SB_MapCursor.layout and SB_Title_01.layout are different in the new build of the game. Replacing these with the current ones made the Mod work as intended. You can most likely better determine what exactly is the problem, and if the y should actually be adapted for the mod or if using the ones from the current version of the game would work fine. Regardless this seems as if it could be fixed quite easily.

I also noticed a bug with the mod, where in the Systems tab, under Controlls, the PS5 Controller was moved too much to the top of the screen and part of the Xbox controller was visible. Modifying the y-coordinate of the Xbox Controller to 390 in SB_Operating_1.layout fixed this for me.

**Comment by Shini1313** [comment]
Some more files that seem to be different and causing problems:
SB_MainMenu_02.layout - This one made the icons of the Affinities of the Ashes of war switched up
SB_Icon_02.layout
SB_Icon_04.layout
SB_Icon_05.layout - I don't know if these three actually caused any problems, I diffed them and they were different, so I replaced them with the current version and the Mod still works as intended

**Comment by losh11** [comment]
@Shini1313 @coolbond1 @smallerYeet this mod has been updated for the latest release of Elden Ring.
