### ISSUE TITLE
< removed >

### ISSUE THREAD

**Issue by finndev** [losh11/EldenRingGamepadUI#7]
< removed >

**Comment by losh11** [comment]
Hey, I've never worked on litevault. Your best course of action to recover your coins is to contact [Daniele Sestagalli](https://ch.linkedin.com/in/daniele-sestagalli-aa293487), who was the CEO of Zulu Republic, the company which owned Litevault. 

I'm gonna close this issue as it's unrelated to this repo, but I hope this helps.
